// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeqfmfgzqzvadhuoqxsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllcWZtZmd6cXp2YWRodW9xeHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTM2ODEsImV4cCI6MjA3NzIyOTY4MX0.bYlOUbII9J0Tw8GvOcKIsP5IrNkYitpHFyjlt-ESzIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});